/**
 * Generates the chart data for the dossier website from the same physics the
 * app runs. Nothing on the site is a hand-typed number; every series here comes
 * out of src/core.
 *
 *   node scripts/site-data.mjs > ../path/to/website/assets/data.js
 *
 * Requires `npm run verify` to have compiled .verify-out first.
 */
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);

const P = require('../.verify-out/core/physics.js');
const A = require('../.verify-out/core/adaptation.js');
const W = require('../.verify-out/core/power.js');
const D = require('../.verify-out/core/dsp.js');

const round = (v, n = 3) => Number(v.toFixed(n));

/* 1. Absorption against frequency, both media ------------------------- */
const absorption = { water: [], air: [] };
for (let kHz = 10; kHz <= 500; kHz += 5) {
  absorption.water.push([kHz, round(P.thorpDbPerKm(kHz), 3)]);
}
for (let kHz = 20; kHz <= 60; kHz += 1) {
  absorption.air.push([kHz, round(P.airAbsorptionDbPerM(kHz) * 1000, 1)]);
}

/* 2. The adaptation sweep: turbidity in, transmit parameters out ------- */
const sweep = [];
for (const ntu of [5, 40, 90, 180, 320, 450, 550, 700, 850, 1000]) {
  const env = { tempC: 26, salinityPpt: 35, turbidityNtu: ntu, depthM: 40 };
  const d = A.decide(env, A.WATER_CONFIG, 0);
  sweep.push({
    ntu,
    fc: round(d.fCentre / 1000, 1),
    bw: round(d.bandwidth / 1000, 1),
    tauMs: round(d.tau * 1000, 2),
    resMm: round(d.resolutionM * 1000, 1),
    rangeM: round(d.maxRangeM, 0),
    snr: round(d.predictedSnrDb, 1),
    gain: round(d.compressionGainDb, 1),
    mode: d.mode,
  });
}

/* 3. Range resolution: unmodulated pulse against the same pulse chirped */
const c = P.soundSpeedWater(26, 35, 40);
const resolution = { soundSpeed: round(c, 1), rows: [] };
for (const tauMs of [0.5, 1, 2, 5, 10]) {
  const tau = tauMs / 1000;
  const bw = 299_000;
  resolution.rows.push({
    tauMs,
    cwM: round(P.rangeResolutionCw(c, tau), 3),
    chirpMm: round(P.rangeResolutionChirp(c, bw) * 1000, 2),
    tbp: Math.round(P.timeBandwidthProduct(tau, bw)),
    gainDb: round(P.compressionGainDb(P.timeBandwidthProduct(tau, bw)), 1),
  });
}

/* 4. Window sidelobe floors ------------------------------------------- */
const windows = Object.entries(D.WINDOW_PSL_DB).map(([k, v]) => [k, v]);

/* 5. Per-ping energy split -------------------------------------------- */
const e = W.pingEnergy(0.0028, 0.82);
const power = {
  wake: round(e.wakeMj, 2),
  sample: round(e.sampleMj, 2),
  compute: round(e.computeMj, 3),
  transmit: round(e.transmitMj, 2),
  total: round(e.totalMj, 2),
  naive: round(e.naiveTotalMj, 2),
  saving: round(e.savingPercent, 1),
  model: W.POWER_MODEL,
};

/* 6. Sound speed against temperature ---------------------------------- */
const soundSpeed = [];
for (let t = 0; t <= 35; t += 1) {
  soundSpeed.push([t, round(P.soundSpeedWater(t, 35, 40), 1)]);
}

const out = { absorption, sweep, resolution, windows, power, soundSpeed,
  generated: new Date().toISOString().slice(0, 10) };

process.stdout.write(
  '/* Generated by scripts/site-data.mjs from src/core. Do not edit by hand. */\n' +
  'window.SEANERGY = ' + JSON.stringify(out) + ';\n'
);
